console.log("letsplay some music");

window.addEventListener("keydown",keyclk);
function keyclk(e){
    let a=e.keyCode;
    if(a==65){
        a1();
    }
    if(a==83){
        a2();
    }
    if(a==68){
        a3();
    }
    if(a==70){
        a4();
    }
    if(a==71){
        a5();
    }
    if(a==72){
        a6();
    }
    if(a==74){
        a7();
    }
    if(a==75){
        b0();
    }
    if(a==76){
        b1();
    }
    if(a==90){
        b2();
    }
    if(a==88){
        b3();
    }
    if(a==67){
        b4();
    }
    if(a==86){
        b5();
    }
    if(a==66){
    b6();
    }
    if(a==78){
        b7();
    }
    if(a==77){
        c1();
    }
    if(a==81){
        c2();
    }
    if(a==87){
        c3();
    }
    if(a==69){
        c4();
    }
    if(a==82){
        c5();
    }
    if(a==84){
        c6();
    }
    if(a==49){
        f1();
    }
    if(a==50){
        f2();
    }
    if(a==51){
        f3();
    }
    if(a==52){
        f4();
    }
    if(a==53){
        f5();
    }
    if(a==54){
        f6();
    }
    if(a==55){
        f7();
    }
    if(a==56){
        f8();
    }
    if(a==57){
        f9();
    }
    if(a==48){
        f10();
    }
    if(a==85){
        f11();
    }
    if(a==73){
        f12();
    }
    if(a==79){
        num1();
    }
    if(a==80){
        num2();
    }
    if(a==115){
        num3();
    }
}
window.onload(alert("PLEASE turn your screen(landscape) for better experience."))
function a1(){
    
    if(document.getElementById("a1").paused){
        document.getElementById("a1").play();
    }
    else{
        document.getElementById("a1").pause();
        document.getElementById("a1").currentTime=0;
        document.getElementById("a1").play();
    }
}
function a2(){
    if(document.getElementById("a2").paused){
        document.getElementById("a2").play();
    }
    else{
        document.getElementById("a2").pause();
        document.getElementById("a2").currentTime=0;
        document.getElementById("a2").play();
    }
}
function a3(){
    if(document.getElementById("a3").paused){
        document.getElementById("a3").play();
    }
    else{
        document.getElementById("a3").pause();
        document.getElementById("a3").currentTime=0;
        document.getElementById("a3").play();
    }
}
function a4(){
    if(document.getElementById("a4").paused){
        document.getElementById("a4").play();
    }
    else{
        document.getElementById("a4").pause();
        document.getElementById("a4").currentTime=0;
        document.getElementById("a4").play();
    }   
}
function a5(){
    if(document.getElementById("a5").paused){
        document.getElementById("a5").play();
    }
    else{
        document.getElementById("a5").pause();
        document.getElementById("a5").currentTime=0;
        document.getElementById("a5").play();
    }
}
function a6(){
    if(document.getElementById("a6").paused){
        document.getElementById("a6").play();
    }
    else{
        document.getElementById("a6").pause();
        document.getElementById("a6").currentTime=0;
        document.getElementById("a6").play();
    }
}
function a7(){
    if(document.getElementById("a7").paused){
        document.getElementById("a7").play();
    }
    else{
        document.getElementById("a7").pause();
        document.getElementById("a7").currentTime=0;
        document.getElementById("a7").play();
    }
}
function b0(){
    if(document.getElementById("b0").paused){
        document.getElementById("b0").play();
    }
    else{
        document.getElementById("b0").pause();
        document.getElementById("b0").currentTime=0;
        document.getElementById("b0").play();
    }
}
function b1(){
    if(document.getElementById("b1").paused){
        document.getElementById("b1").play();
    }
    else{
        document.getElementById("b1").pause();
        document.getElementById("b1").currentTime=0;
        document.getElementById("b1").play();
    }
}
function b2(){
    if(document.getElementById("b2").paused){
        document.getElementById("b2").play();
    }
    else{
        document.getElementById("b2").pause();
        document.getElementById("b2").currentTime=0;
        document.getElementById("b2").play();
    }
}
function b3(){
    if(document.getElementById("b3").paused){
        document.getElementById("b3").play();
    }
    else{
        document.getElementById("b3").pause();
        document.getElementById("b3").currentTime=0;
        document.getElementById("b3").play();
    }
}
function b4(){
    if(document.getElementById("b4").paused){
        document.getElementById("b4").play();
    }
    else{
        document.getElementById("b4").pause();
        document.getElementById("b4").currentTime=0;
        document.getElementById("b4").play();
    }
}
function b5(){
    if(document.getElementById("b5").paused){
        document.getElementById("b5").play();
    }
    else{
        document.getElementById("b5").pause();
        document.getElementById("b5").currentTime=0;
        document.getElementById("b5").play();
    }
}
function b6(){
    if(document.getElementById("b6").paused){
        document.getElementById("b6").play();
    }
    else{
        document.getElementById("b6").pause();
        document.getElementById("b6").currentTime=0;
        document.getElementById("b6").play();
    }
}
function b7(){
    if(document.getElementById("b7").paused){
        document.getElementById("b7").play();
    }
    else{
        document.getElementById("b7").pause();
        document.getElementById("b7").currentTime=0;
        document.getElementById("b7").play();
    }
}
function c1(){
    if(document.getElementById("c1").paused){
        document.getElementById("c1").play();
    }
    else{
        document.getElementById("c1").pause();
        document.getElementById("c1").currentTime=0;
        document.getElementById("c1").play();
    }
}
function c2(){
    if(document.getElementById("c2").paused){
        document.getElementById("c2").play();
    }
    else{
        document.getElementById("c2").pause();
        document.getElementById("c2").currentTime=0;
        document.getElementById("c2").play();
    }
}
function c3(){
    if(document.getElementById("c3").paused){
        document.getElementById("c3").play();
    }
    else{
        document.getElementById("c3").pause();
        document.getElementById("c3").currentTime=0;
        document.getElementById("c3").play();
    }
}
function c4(){
    if(document.getElementById("c4").paused){
        document.getElementById("c4").play();
    }
    else{
        document.getElementById("c4").pause();
        document.getElementById("c4").currentTime=0;
        document.getElementById("c4").play();
    }
}
function c5(){
    if(document.getElementById("c5").paused){
        document.getElementById("c5").play();
    }
    else{
        document.getElementById("c5").pause();
        document.getElementById("c5").currentTime=0;
        document.getElementById("c5").play();
    }
}
function c6(){
    if(document.getElementById("c6").paused){
        document.getElementById("c6").play();
    }
    else{
        document.getElementById("c6").pause();
        document.getElementById("c6").currentTime=0;
        document.getElementById("c6").play();
    }
}
function f1(){
    if(document.getElementById("f1").paused){
        document.getElementById("f1").play();
    }
    else{
        document.getElementById("f1").pause();
        document.getElementById("f1").currentTime=0;
        document.getElementById("f1").play();
    }
}
function f2(){
    if(document.getElementById("f2").paused){
        document.getElementById("f2").play();
    }
    else{
        document.getElementById("f2").pause();
        document.getElementById("f2").currentTime=0;
        document.getElementById("f2").play();
    }
}
function f3(){
    if(document.getElementById("f3").paused){
        document.getElementById("f3").play();
    }
    else{
        document.getElementById("f3").pause();
        document.getElementById("f3").currentTime=0;
        document.getElementById("f3").play();
    }
}
function f4(){
    if(document.getElementById("f4").paused){
        document.getElementById("f4").play();
    }
    else{
        document.getElementById("f4").pause();
        document.getElementById("f4").currentTime=0;
        document.getElementById("f4").play();
    }
}
function f5(){
    if(document.getElementById("f5").paused){
        document.getElementById("f5").play();
    }
    else{
        document.getElementById("f5").pause();
        document.getElementById("f5").currentTime=0;
        document.getElementById("f5").play();
    }
}
function f6(){
    if(document.getElementById("f6").paused){
        document.getElementById("f6").play();
    }
    else{
        document.getElementById("f6").pause();
        document.getElementById("f6").currentTime=0;
        document.getElementById("f6").play();
    }
}
function f7(){
    if(document.getElementById("f7").paused){
        document.getElementById("f7").play();
    }
    else{
        document.getElementById("f7").pause();
        document.getElementById("f7").currentTime=0;
        document.getElementById("f7").play();
    }
}
function f8(){
    if(document.getElementById("f8").paused){
        document.getElementById("f8").play();
    }
    else{
        document.getElementById("f8").pause();
        document.getElementById("f8").currentTime=0;
        document.getElementById("f8").play();
    }
}
function f9(){
    if(document.getElementById("f9").paused){
        document.getElementById("f9").play();
    }
    else{
        document.getElementById("f9").pause();
        document.getElementById("f9").currentTime=0;
        document.getElementById("f9").play();
    }
}
function f10(){
    if(document.getElementById("f10").paused){
        document.getElementById("f10").play();
    }
    else{
        document.getElementById("f10").pause();
        document.getElementById("f10").currentTime=0;
        document.getElementById("f10").play();
    }
}
function f11(){
    if(document.getElementById("f11").paused){
        document.getElementById("f11").play();
    }
    else{
        document.getElementById("f11").pause();
        document.getElementById("f11").currentTime=0;
        document.getElementById("f11").play();
    }
}
function f12(){
    if(document.getElementById("f12").paused){
        document.getElementById("f12").play();
    }
    else{
        document.getElementById("f12").pause();
        document.getElementById("f12").currentTime=0;
        document.getElementById("f12").play();
    }
}
function num1(){
    if(document.getElementById("num1").paused){
        document.getElementById("num1").play();
    }
    else{
        document.getElementById("num1").pause();
        document.getElementById("num1").currentTime=0;
        document.getElementById("num1").play();
    }
}
function num2(){
    if(document.getElementById("num2").paused){
        document.getElementById("num2").play();
    }
    else{
        document.getElementById("num2").pause();
        document.getElementById("num2").currentTime=0;
        document.getElementById("num2").play();
    }
}
function num3(){
    if(document.getElementById("num3").paused){
        document.getElementById("num3").play();
    }
    else{
        document.getElementById("num3").pause();
        document.getElementById("num3").currentTime=0;
        document.getElementById("num3").play();
    }
}
